---
abstract: 'Constant data for Data::Bus.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Const-Bus
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Data::Bus: 0.03
  Data::Bus::Order: 0.03
  Data::Bus::Term: 0.03
  Data::Const: 0
  Data::ExternalId: 0
  Data::Person: 0
  DateTime: 0
  Unicode::UTF8: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Data-Const-Bus/issues
  homepage: https://github.com/michal-josef-spacek/Data-Const-Bus
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Data-Const-Bus
version: '0.01'
